# Generated by Django 3.2.5 on 2021-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('INWORK', 'В работе'), ('CLOSED', 'Закрыта')], max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
