# Generated by Django 3.2.5 on 2021-07-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
