# Generated by Django 3.2.5 on 2021-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
