# Generated by Django 3.2.5 on 2021-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0005_task_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
