# Generated by Django 3.2.5 on 2021-07-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0006_task_date_close'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_add_task', 'Добавление задачи'),)},
        ),
    ]
