# Generated by Django 3.2.5 on 2021-07-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
