# Generated by Django 3.2.5 on 2021-07-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0009_auto_20210722_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
