# Generated by Django 3.2.5 on 2021-07-22 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0009_auto_20210722_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 16, 13, 37, 406743), verbose_name='Дата создания'),
        ),
    ]
