# Generated by Django 3.2.5 on 2021-07-26 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0010_alter_task_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 16, 35, 39, 496864), verbose_name='Дата создания'),
        ),
    ]
