# Generated by Django 3.2.5 on 2021-07-27 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0011_alter_task_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 10, 29, 42, 511767), verbose_name='Дата создания'),
        ),
    ]
