# Generated by Django 3.2.5 on 2022-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskBoard', '0015_auto_20220211_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworkinghours',
            name='timeWorked',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отработанное время'),
        ),
    ]
